config/routes.rb
EarningsDateFinder::Application.routes.draw do
  resources :earnings
  match "import" => "earnings#import", :as => "import_earnings", :via => [:post]

  root :to => "earnings#index"

end

app/models/earning.rb
class Earning < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/earnings_controller.rb
require 'open-uri'

class EarningsController < ApplicationController
  # GET /earnings
  # GET /earnings.xml
  def index
    @earnings = Earning.find(:all, :order => "released_at DESC, name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @earnings }
    end
  end

  # GET /earnings/1
  # GET /earnings/1.xml
  def show
    @earning = Earning.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @earning }
    end
  end

  # GET /earnings/new
  # GET /earnings/new.xml
  def new
    @earning = Earning.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @earning }
    end
  end

  # GET /earnings/1/edit
  def edit
    @earning = Earning.find(params[:id])
  end

  # POST /earnings
  # POST /earnings.xml
  def create
    @earning = Earning.new(params[:earning])

    respond_to do |format|
      if @earning.save
        format.html { redirect_to(@earning, :notice => 'Earning was successfully created.') }
        format.xml  { render :xml => @earning, :status => :created, :location => @earning }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @earning.errors, :status => :unprocessable_entity }
      end
    end
  end

  # POST /import
  def import
    from_args = params[:from_date].split('-')
    from_date = Time.local(from_args[0], from_args[1], from_args[2])

    to_args = params[:to_date].split('-')
    to_date = Time.local(to_args[0], to_args[1], to_args[2])

    while from_date <= to_date
      if from_date.weekday?
        begin
          # load page...
          page = Nokogiri::HTML(open("http://biz.yahoo.com/research/earncal/#{from_date.strftime('%Y%m%d')}.html"))
          # find all tables...
          tables = page.xpath("//table")
          # the 6th table is the one we want...
          table_node = tables[6]
          # all the rows we want...
          table_node.children[2..table_node.children.length-2].each do |stock|
            values = stock.children
            earning = Earning.new(:name => values[0].text,
                                  :cusip => values[1].text,
                                  :released_at => from_date,
                                  :at_time => values[3].text
                                  )
            earning.save!
          end
        rescue Exception => e
        end
      end
      # sleep for a bit to not overwhelm their servers...
      sleep 3 unless from_date == to_date

      # iterate and break the loop once we're past to_date...
      from_date = from_date + 1.day
    end

    redirect_to :action => "index"
  end

  # PUT /earnings/1
  # PUT /earnings/1.xml
  def update
    @earning = Earning.find(params[:id])

    respond_to do |format|
      if @earning.update_attributes(params[:earning])
        format.html { redirect_to(@earning, :notice => 'Earning was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @earning.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /earnings/1
  # DELETE /earnings/1.xml
  def destroy
    @earning = Earning.find(params[:id])
    @earning.destroy

    respond_to do |format|
      format.html { redirect_to(earnings_url) }
      format.xml  { head :ok }
    end
  end
end

class Time
  def weekday?
    self.wday != 0 and self.wday != 6
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/earnings_helper.rb
module EarningsHelper
end

app/views/earnings/_form.html.erb
<%= form_for(@earning) do |f| %>
  <% if @earning.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@earning.errors.count, "error") %> prohibited this earning from being saved:</h2>

      <ul>
      <% @earning.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cusip %><br />
    <%= f.text_field :cusip %>
  </div>
  <div class="field">
    <%= f.label :estimate %><br />
    <%= f.text_field :estimate %>
  </div>
  <div class="field">
    <%= f.label :at_time %><br />
    <%= f.text_field :at_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/earnings/edit.html.erb
<h1>Editing earning</h1>

<%= render 'form' %>

<%= link_to 'Show', @earning %> |
<%= link_to 'Back', earnings_path %>

app/views/earnings/index.html.erb
<%= content_for :ready do %>
    $(function() {
      $("#from_date").datepicker({ dateFormat: 'yy-mm-dd' });
      $("#to_date").datepicker({ dateFormat: 'yy-mm-dd' });
    });
<% end %>

<h1>Listing earnings</h1>

<%= form_tag(import_earnings_path, :confirm=> 'Are you sure you would like to import earnings?') do %>
  <%= text_field_tag 'from_date', nil, :placeholder => 'From Date', :id => 'from_date' %>
  <%= text_field_tag 'to_date', nil, :placeholder => 'To Date', :id => 'to_date' %>
  <div><%= submit_tag 'Import' %></div>
<% end %>

<table>
  <tr class='header-row'>
    <th>Name</th>
    <th>Cusip</th>
    <th>Earnings Date</th>
    <th>Estimate</th>
    <th>At time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @earnings.each do |earning| %>
  <tr>
    <td><%= earning.name %></td>
    <td><%= earning.cusip %></td>
    <td class='centered'><%= earning.released_at.strftime('%m-%d-%Y') %></td>
    <td><%= earning.estimate %></td>
    <td class='centered'><%= earning.at_time %></td>
    <td><%#= link_to 'Show', earning %></td>
    <td><%#= link_to 'Edit', edit_earning_path(earning) %></td>
    <td><%#= link_to 'Destroy', earning, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Earning', new_earning_path %>

app/views/earnings/new.html.erb
<h1>New earning</h1>

<%= render 'form' %>

<%= link_to 'Back', earnings_path %>

app/views/earnings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @earning.name %>
</p>

<p>
  <b>Cusip:</b>
  <%= @earning.cusip %>
</p>

<p>
  <b>Estimate:</b>
  <%= @earning.estimate %>
</p>

<p>
  <b>At time:</b>
  <%= @earning.at_time %>
</p>


<%= link_to 'Edit', edit_earning_path(@earning) %> |
<%= link_to 'Back', earnings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EarningsDateFinder</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'jquery-1.6.2.min.js' %>
  <%= javascript_include_tag 'jquery-ui-1.8.16.custom.min.js' %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">
    $(document).ready(function() {
      <%= yield(:ready) %>
    });
  </script>
</head>
<body>

<%= yield %>

</body>
</html>